### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by Kauto** [WoutervdBrink/Laravel-Lighthouse-Test#7]
Hi,

I like your package. I would love to use it for my Larvel 8 + Lighthouse project. But I get the error
```
knevelina/laravel-lighthouse-test[1.2.0, ..., 1.2.1] require illuminate/support ^7.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
```

Would be great if you could support Larvel 8.

Best

**Comment by WoutervdBrink** [comment]
Hi Kauto,

Thank you for your kind message. Unfortunately, I've stopped using Lighthouse and thus have also stopped further development of this package.

This package was developed in close cooperation with the Lighthouse developers and some features have been merged upstream. You should check out the Testing chapter of the documentation: https://lighthouse-php.com/5.2/testing/phpunit.html#setup

You could also try bumping the version requirement via a pull request, but I cannot easily verify if that'd work as I don't have a Lighthouse project ready. As I'm not updating the library, I wouldn't recommend using it in production.

I hope this helps.

Wouter

**Comment by Kauto** [comment]
Hi Wouter,

Thank you for your answer! As you suggested I'm now using the default test features of lighthouse.

I wish you the best for your future.

Kauto
